import type { CSSProperties } from "react";

export const s = {
  page: { display: "flex", flexDirection: "column", height: "100%" } satisfies CSSProperties,
  split: { display: "flex", flex: 1, minHeight: 0 } satisfies CSSProperties,
  left: {
    width: 280,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  leftHead: { padding: "18px 16px 10px" } satisfies CSSProperties,
  label: { fontSize: 11, fontWeight: 600, letterSpacing: 0.8, color: "var(--text-muted)", textTransform: "uppercase" } satisfies CSSProperties,
  root: { fontSize: 13, color: "var(--text-secondary)", marginTop: 6 } satisfies CSSProperties,
  toolbar: { display: "flex", padding: "0 12px 8px" } satisfies CSSProperties,
  list: { flex: 1, overflow: "auto", padding: "0 8px" } satisfies CSSProperties,
  item: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    textAlign: "left",
    padding: "9px 10px",
    marginBottom: 2,
    borderRadius: 8,
    border: "none",
    background: active ? "var(--bg-hover)" : "none",
    color: active ? "var(--text-primary, var(--text))" : "var(--text-secondary)",
    cursor: "pointer",
    fontSize: 13,
  }),
  itemIcon: (active: boolean): CSSProperties => ({
    flexShrink: 0,
    color: active ? "var(--accent)" : "var(--text-muted)",
  }),
  itemPath: { flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" } satisfies CSSProperties,
  right: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  docHead: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "0 24px",
    minHeight: 64,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  docPath: { fontSize: 15, fontWeight: 600 } satisfies CSSProperties,
  segment: {
    display: "inline-flex",
    padding: 2,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  segmentItem: {
    fontSize: 12,
    fontWeight: 600,
    padding: "4px 12px",
    borderRadius: 6,
    background: "var(--bg-hover)",
    color: "var(--text-primary, var(--text))",
  } satisfies CSSProperties,
  usedBy: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  content: { flex: 1, overflow: "auto", padding: "28px 32px" } satisfies CSSProperties,
  contentInner: { maxWidth: 760 } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    padding: "12px 16px",
    borderTop: "1px solid var(--border)",
    fontSize: 12,
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  dot: { width: 6, height: 6, borderRadius: "50%", background: "var(--ok)", flexShrink: 0 } satisfies CSSProperties,
  state: { padding: 24 } satisfies CSSProperties,
} as const;
