import type { CSSProperties } from "react";

export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 18,
  } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  repoName: { color: "var(--accent-text)" } satisfies CSSProperties,
  subtitle: { fontSize: 14, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,
  headerActions: { display: "flex", alignItems: "center", gap: 8, flexShrink: 0 } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  } satisfies CSSProperties,
  toolbarLeft: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  acceptedMeta: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  card: (accepted: boolean, rejected: boolean): CSSProperties => ({
    display: "flex",
    gap: 16,
    padding: "14px 16px",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 3,
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopColor: "var(--border)",
    borderRightColor: "var(--border)",
    borderBottomColor: "var(--border)",
    borderLeftColor: accepted ? "var(--ok)" : "var(--border)",
    opacity: rejected ? 0.72 : 1,
  }),
  cardMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  cardActions: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flexShrink: 0,
    width: 140,
  } satisfies CSSProperties,
  title: {
    fontSize: 15,
    fontWeight: 600,
    margin: 0,
    lineHeight: 1.35,
  } satisfies CSSProperties,
  titleInput: {
    width: "100%",
    fontSize: 15,
    fontWeight: 600,
    background: "var(--bg-surface)",
    border: "1px solid var(--border-strong)",
    borderRadius: 6,
    color: "var(--text-primary)",
    padding: "4px 8px",
  } satisfies CSSProperties,
  evidenceRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  } satisfies CSSProperties,
  snippet: {
    marginTop: 8,
    padding: "10px 12px",
    borderRadius: 8,
    background: "var(--bg-primary)",
    fontSize: 12,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    color: "var(--text-secondary)",
    whiteSpace: "pre-wrap",
    overflow: "auto",
    maxHeight: 88,
  } satisfies CSSProperties,
  confidence: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  confBar: { width: 88, flexShrink: 0 } satisfies CSSProperties,
} as const;
