import type { CSSProperties } from "react";

export const s = {
  stack: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  emptyCard: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: "56px 18px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    gap: 10,
  } satisfies CSSProperties,
  emptyIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    display: "grid",
    placeItems: "center",
    background: "var(--bg-hover)",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  emptyTitle: { fontSize: 15, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 6 } satisfies CSSProperties,
  notice: {
    fontSize: 13,
    color: "var(--text-secondary)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--danger, #ef4444)" } satisfies CSSProperties,
  // risk areas
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  risk: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "8px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  riskHead: { display: "flex", alignItems: "flex-start", gap: 10 } satisfies CSSProperties,
  riskBody: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  riskTitle: { display: "flex", alignItems: "center", gap: 8, fontSize: 13.5, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  severityIcon: (color: string): CSSProperties => ({ color, display: "inline-flex", flexShrink: 0 }),
  explanation: { margin: 0, fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  link: {
    background: "none",
    border: 0,
    padding: 0,
    cursor: "pointer",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    color: "var(--accent-text, var(--accent))",
    textAlign: "left",
  } satisfies CSSProperties,
  chevron: {
    background: "none",
    border: 0,
    borderLeft: "1px solid var(--border)",
    alignSelf: "stretch",
    padding: "0 8px",
    cursor: "pointer",
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
  } satisfies CSSProperties,
  // review focus
  focusItem: { display: "flex", alignItems: "baseline", gap: 8, fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  bullet: { fontSize: 8, color: "var(--accent-text, var(--accent))" } satisfies CSSProperties,
  count: {
    fontSize: 11.5,
    fontWeight: 700,
    padding: "1px 7px",
    borderRadius: 4,
    background: "var(--accent-bg)",
    color: "var(--accent-text, var(--accent))",
  } satisfies CSSProperties,
} as const;
