import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  row: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" } satisfies CSSProperties,
  summary: { margin: 0, fontSize: 14, lineHeight: 1.55, color: "var(--text-primary)" } satisfies CSSProperties,
  subTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  risk: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  severity: (color: string): CSSProperties => ({
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    color,
    border: `1px solid ${color}`,
    borderRadius: 4,
    padding: "1px 6px",
  }),
  riskTitle: { fontSize: 13.5, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  explanation: { margin: 0, fontSize: 13, color: "var(--text-secondary)", lineHeight: 1.5 } satisfies CSSProperties,
  link: {
    background: "none",
    border: 0,
    padding: 0,
    cursor: "pointer",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12.5,
    color: "var(--accent-text, var(--accent))",
    textAlign: "left",
  } satisfies CSSProperties,
  toggle: {
    background: "none",
    border: 0,
    padding: 0,
    cursor: "pointer",
    fontSize: 12,
    color: "var(--text-muted)",
    textDecoration: "underline",
  } satisfies CSSProperties,
  focusItem: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  muted: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  notice: {
    fontSize: 13,
    color: "var(--text-secondary)",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "8px 10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--danger, #ef4444)" } satisfies CSSProperties,
} as const;
