import type { CSSProperties } from "react";

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  summaryRow: {
    display: "flex",
    alignItems: "center",
    gap: 20,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  stat: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  statValue: {
    fontSize: 15,
    fontWeight: 700,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 6,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 13,
  } satisfies CSSProperties,
  bannerText: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  } satisfies CSSProperties,
  tree: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  node: {
    border: "1px solid var(--border)",
    borderRadius: 6,
    overflow: "hidden",
  } satisfies CSSProperties,
  nodeHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    cursor: "pointer",
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  nodeName: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
    color: "var(--text-primary)",
    flex: 1,
  } satisfies CSSProperties,
  nodeCallerCount: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  nodeBody: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    padding: "10px 12px 12px 30px",
  } satisfies CSSProperties,
  callerRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  pillRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 4,
  } satisfies CSSProperties,
  empty: {
    fontSize: 13,
    color: "var(--text-muted)",
    fontStyle: "italic",
    padding: "4px 0",
  } satisfies CSSProperties,
  error: {
    fontSize: 13,
    color: "var(--crit)",
  } satisfies CSSProperties,
  viewToggle: {
    marginLeft: "auto",
    display: "flex",
    gap: 2,
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: 2,
  } satisfies CSSProperties,
  viewToggleButton: (active: boolean): CSSProperties => ({
    border: "none",
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    fontSize: 12,
    fontWeight: active ? 600 : 500,
    padding: "4px 10px",
    borderRadius: 4,
    cursor: "pointer",
  }),
  graphWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  } satisfies CSSProperties,
  graphSvg: {
    display: "block",
    width: "100%",
  } satisfies CSSProperties,
  graphLegend: {
    display: "flex",
    gap: 16,
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  graphLegendItem: {
    display: "flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  graphLegendSwatch: (color: string): CSSProperties => ({
    width: 10,
    height: 10,
    borderRadius: 3,
    border: `1.5px solid ${color}`,
  }),
  // ---- Prior PRs (task 5.6) ----
  priorWrap: {
    display: "flex",
    flexDirection: "column",
  } satisfies CSSProperties,
  priorDivider: {
    borderTop: "1px solid var(--border)",
    marginBottom: 10,
  } satisfies CSSProperties,
  priorHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    cursor: "pointer",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  priorTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
    flex: 1,
  } satisfies CSSProperties,
  priorBody: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    paddingTop: 10,
  } satisfies CSSProperties,
  priorItem: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    padding: "8px 10px",
    borderRadius: 6,
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  priorLink: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  priorMeta: {
    fontSize: 12,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  priorFiles: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  priorNotes: {
    fontSize: 12,
    color: "var(--text-muted)",
    fontStyle: "italic",
  } satisfies CSSProperties,
} as const;
