import type { CSSProperties } from "react";

export const s = {
  page: {
    display: "flex",
    alignItems: "flex-start",
    gap: 40,
    padding: "24px 32px 44px",
    maxWidth: 1400,
    margin: "0 auto",
  } satisfies CSSProperties,
  column: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 18,
  } satisfies CSSProperties,
  h1: {
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  repoName: {
    color: "var(--accent-text)",
    fontFamily: "var(--font-mono)",
  } satisfies CSSProperties,
  subtitle: {
    fontSize: 14,
    color: "var(--text-secondary)",
    marginTop: 4,
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    marginBottom: 12,
    borderRadius: 8,
    fontSize: 13,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  note: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginBottom: 8,
  } satisfies CSSProperties,
  list: {
    margin: "8px 0 0",
    paddingLeft: 20,
    fontSize: 14,
    lineHeight: 1.6,
  } satisfies CSSProperties,
  muted: {
    color: "var(--text-secondary)",
    fontSize: 13,
  } satisfies CSSProperties,
  footer: {
    marginTop: 32,
    paddingTop: 12,
    borderTop: "1px solid var(--border)",
    display: "flex",
    flexWrap: "wrap",
    gap: 12,
    fontSize: 12,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  sr: {
    minHeight: 18,
    fontSize: 12,
    color: "var(--ok)",
    marginBottom: 4,
  } satisfies CSSProperties,
  shareField: {
    width: "100%",
    marginTop: 8,
    padding: "6px 10px",
    fontSize: 12.5,
    background: "var(--bg-primary)",
    color: "var(--text-primary)",
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
  hint: {
    fontSize: 12,
    color: "var(--text-secondary)",
    marginTop: 6,
  } satisfies CSSProperties,
  // TOC
  toc: {
    position: "sticky",
    top: 24,
    width: 230,
    flexShrink: 0,
  } satisfies CSSProperties,
  tocTitle: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-secondary)",
    padding: "0 12px",
    marginBottom: 10,
  } satisfies CSSProperties,
  tocItem: (active: boolean): CSSProperties => ({
    display: "block",
    width: "100%",
    textAlign: "left",
    padding: "7px 12px",
    fontSize: 14,
    background: "transparent",
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
    fontWeight: active ? 600 : 400,
    borderLeft: `2px solid ${active ? "var(--accent)" : "transparent"}`,
  }),
  // card
  card: {
    marginBottom: 18,
    padding: 20,
    borderRadius: 12,
    background: "var(--bg-surface)",
    border: "1px solid var(--border)",
    scrollMarginTop: 16,
  } satisfies CSSProperties,
  h2: { margin: 0, fontSize: 18, fontWeight: 600 } satisfies CSSProperties,
  toggle: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    width: "100%",
    padding: 0,
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: "inherit",
    fontWeight: "inherit",
    textAlign: "left",
  } satisfies CSSProperties,
  iconBox: {
    display: "inline-grid",
    placeItems: "center",
    width: 36,
    height: 36,
    borderRadius: 8,
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    flexShrink: 0,
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    marginLeft: "auto",
    color: "var(--text-secondary)",
    display: "inline-flex",
    transform: open ? "rotate(180deg)" : undefined,
  }),
  cardBody: { marginTop: 16 } satisfies CSSProperties,
  // rows
  rows: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginBottom: 14,
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    minWidth: 0,
  } satisfies CSSProperties,
  ellipsis: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  stepRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "8px 12px",
    borderRadius: 8,
    background: "var(--bg-primary)",
    border: "1px solid var(--border)",
    minWidth: 0,
  } satisfies CSSProperties,
  stepIndex: {
    width: 14,
    fontSize: 12,
    color: "var(--text-muted)",
    flexShrink: 0,
  } satisfies CSSProperties,
  stepText: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  reading: {
    listStyle: "none",
    margin: "0 0 14px",
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  } satisfies CSSProperties,
  readingItem: {
    display: "flex",
    gap: 12,
    alignItems: "flex-start",
    minWidth: 0,
  } satisfies CSSProperties,
  badge: {
    display: "inline-grid",
    placeItems: "center",
    width: 24,
    height: 24,
    borderRadius: "50%",
    background: "var(--accent-bg)",
    color: "var(--accent-text)",
    fontSize: 12,
    fontWeight: 600,
    flexShrink: 0,
  } satisfies CSSProperties,
  taskCard: {
    minWidth: 0,
    padding: 14,
    borderRadius: 10,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
  } satisfies CSSProperties,
  taskTitle: {
    fontWeight: 600,
    fontSize: 14,
    marginBottom: 6,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  headerWrap: { marginBottom: 18 } satisfies CSSProperties,
  headerRow: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 14,
    marginBottom: 0,
  } satisfies CSSProperties,
  shrinkable: { minWidth: 0 } satisfies CSSProperties,
  readingBody: { minWidth: 0, flex: 1 } satisfies CSSProperties,
  mutedEllipsis: {
    color: "var(--text-secondary)",
    fontSize: 13,
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  tasksWrapGap: { marginBottom: 14 } satisfies CSSProperties,
  openLink: {
    flexShrink: 0,
    fontSize: 12.5,
    padding: "5px 9px",
    border: "1px solid var(--border)",
    borderRadius: 6,
  } satisfies CSSProperties,
};
