import type { CSSProperties } from "react";

export const s = {
  head: { display: "flex", alignItems: "center", gap: 12, marginBottom: 8 } satisfies CSSProperties,
  title: { fontSize: 18, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  count: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    padding: "2px 8px",
    borderRadius: 4,
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", margin: "0 0 18px" } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    width: 240,
    padding: "8px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text)",
    fontSize: 13,
  } satisfies CSSProperties,
  rowWrap: { marginBottom: 8 } satisfies CSSProperties,
  row: (dim: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    opacity: dim ? 0.6 : 1,
  }),
  handle: (on: boolean): CSSProperties => ({
    cursor: on ? "grab" : "default",
    color: "var(--text-muted)",
    display: "inline-flex",
    opacity: on ? 1 : 0.35,
  }),
  name: { fontSize: 14, fontWeight: 600, color: "var(--text-primary, var(--text))" } satisfies CSSProperties,
  dir: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  chip: (color: string): CSSProperties => ({
    fontSize: 12,
    fontWeight: 600,
    color,
    background: color + "1a",
    padding: "1px 8px",
    borderRadius: 4,
    flexShrink: 0,
  }),
  tokens: { fontSize: 11, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  previewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-secondary)",
    background: "none",
    border: "1px solid var(--border)",
    borderRadius: 6,
    padding: "5px 10px",
    cursor: "pointer",
  } satisfies CSSProperties,
  attachBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 14,
    fontSize: 13,
    color: "var(--text)",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong, var(--border))",
    borderRadius: 8,
    padding: "7px 14px",
    cursor: "pointer",
  } satisfies CSSProperties,
  drawerTitle: { display: "flex", alignItems: "center", gap: 10, fontSize: 15 } satisfies CSSProperties,
  drawerMeta: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  metaItem: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  drawerBody: {
    padding: "20px 24px",
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;

export const KIND_COLOR: Record<string, string> = {
  specs: "#3b82f6",
  docs: "#10b981",
  insights: "#f59e0b",
};
