import type { CSSProperties } from "react";

export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 20, maxWidth: 1000 } satisfies CSSProperties,
  sectionHead: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12 } satisfies CSSProperties,
  label: { fontSize: 11, fontWeight: 600, letterSpacing: "0.08em", color: "var(--text-muted)" } satisfies CSSProperties,
  tiles: { display: "flex", gap: 12 } satisfies CSSProperties,
  link: { fontSize: 13, color: "var(--text-secondary)", textDecoration: "none" } satisfies CSSProperties,
  casesHead: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  casesTitle: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  pill: {
    fontSize: 12,
    padding: "2px 8px",
    borderRadius: 6,
    background: "var(--ok-bg, rgba(46,160,67,.15))",
    color: "var(--ok)",
    fontWeight: 600,
  } satisfies CSSProperties,
  spacer: { flex: 1 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "14px 16px",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border)",
    borderRadius: 9,
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowName: { fontWeight: 600, fontSize: 14 } satisfies CSSProperties,
  rowSub: { fontSize: 13, color: "var(--text-secondary)", marginTop: 2 } satisfies CSSProperties,
  kind: {
    fontSize: 12,
    color: "var(--text-secondary)",
    background: "var(--bg-surface)",
    padding: "3px 8px",
    borderRadius: 6,
  } satisfies CSSProperties,
  actions: { display: "flex", gap: 4 } satisfies CSSProperties,
  muted: { fontSize: 14, color: "var(--text-secondary)" } satisfies CSSProperties,
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13 } satisfies CSSProperties,
  th: {
    textAlign: "left",
    padding: "8px 10px",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.06em",
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  td: { padding: "9px 10px", borderBottom: "1px solid var(--border)" } satisfies CSSProperties,
} as const;
